version: '3.8'
services:
  backend:
    container_name: backend
    build:
      context: your-backend-directory
      dockerfile: Dockerfile # same as of your docker file name
    environment:
      - ENV_NAME=value # your environtment varibles value
    volumes:
      - ./directory-path:/direcotory-end-name
    ports:
      - 8080:8080
    depends_on:
      - postgresql_server
    restart: unless-stopped

  frontend:
    container_name: backend
    build:
      context: your-backend-directory
      dockerfile: Dockerfile # same as of your docker file name
    environment:
      - ENV_NAME=value # your environtment varibles value
    volumes:
      - ./directory-path:/direcotory-end-name
    ports:
      - 3000:3000
    restart: always

  postgresql:
    image: postgres:12-alpine
    container_name: postgres_server
    restart: always
    env_file: ./.env
    environment:
      - DEBUG=${DEBUG} # method 1
      - POSTGRES_USER: ${POSTGRES_USER} # method 2
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - app_db:/var/lib/postgresql

volumes:
  app_db:

networks:
  node-network:
    driver: bridge
