version: '3.8'

# From the setup below, mongodb_server will run first, then server, and finally client
services:
  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '5000:5000'
    env_file: ./.env
    environment:
      - DB_HOST=mongodb_server
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    depends_on:
      - mongodb

  # Client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    container_name: frontend
    ports:
      - '80:80'
    depends_on:
      - server

  # Database service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    restart: always
    env_file: ./.env
    environment:
      - DEBUG=${DEBUG} # method 1
      - MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER} # method 2
      - MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      - MONGO_URI: ${MONGODB_URI} # method 3
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - app_db:/data/db:rw # mongodb data will be stored in app_db volume below

# define volumes -> mongodb data will be stored in app_db volume
volumes:
  app_db:

networks:
  my-app-network:
    driver: bridge
